### ISSUE TITLE
Issue caching the `.cache` directory

### ISSUE THREAD

**Issue by ehmicky** [jlengstorf/netlify-plugin-gatsby-cache#10]
At the moment, this plugin caches `PUBLISH_DIR/../.cache` (`PUBLISH_DIR` was previously called `BUILD_DIR`). However when no "Publish directory" is set by the user, it defaults to the repository root directory. 

This means the `{repositoryRoot}/../.cache` ends up being cached, which is probably not intended?

**Comment by jlengstorf** [comment]
if we fix #8 this will be resolved automatically — Gatsby _always_ puts `public` and `.cache` next to each other

**Comment by ehmicky** [comment]
This turned out not to be an issue (see #8).
