### ISSUE TITLE
Some users report performance issues

### ISSUE THREAD

**Issue by ehmicky** [jlengstorf/netlify-plugin-gatsby-cache#13]
Some users report that this Build plugin makes builds slower instead of faster.

I personally have not encountered this issue: this plugin makes my builds faster. Reasons why builds might be slower could include though:
  - writing/reading and upload/downloading the cached `public` and `.cache` directories takes more time than it saves
  - a bug in `utils.cache`

To be able to fix this problem, I would need to reproduce it first though either:
  - by reproducing it myself
  - by having someone else point to a Deploy that exhibits this behavior. 

@dsoaress you interacted on the following issue: https://github.com/netlify/build/issues/1125, do you have a Deploy that exhibits this behavior by any chance?

@marisamorby, is there any chance you found some Deploys that do?

**Comment by dsoaress** [comment]
Hi @ehmicky, I do.

[With Netlify Build and netlify-plugin-gatsby-cache](https://app.netlify.com/sites/diego-haymann/deploys/5e932f813be1380007f10b11).

[Only with Netlify Build](https://app.netlify.com/sites/diego-haymann/deploys/5e9352b0e8566e00069bcf01).

[Without Netlify Build](https://app.netlify.com/sites/diego-haymann/deploys/5e935464abd8cc1cd3285000).

**Comment by ehmicky** [comment]
Thanks, this helps a lot!

So this is where the performance difference is coming from:
  - When a repository is using a Build plugin that is not in their `package.json`, Netlify automatically installs it. For the deploy above (only one plugin), this adds 1 minute to the build.
  - `yarn install` performed in the beginning of the build takes 51 seconds instead of 1 seconds. This is done inside the buildbot (not Netlify Build) so this might be a caching issue there.

I will add issues for the two problems above.

Now the `netlify-plugin-gatsby-cache` plugin itself does reduce the time to perform `gatsby build` from 109 seconds to 72 seconds. So the issue is not about that plugin but about Netlify Build and the buildbot.
