### ISSUE TITLE
specify alternate cache location

### ISSUE THREAD

**Issue by davidosomething** [jlengstorf/netlify-plugin-gatsby-cache#16]
The typical build cache location (/.cache) is not in the publish location (/public)
https://www.gatsbyjs.org/docs/gatsby-project-structure/

how might one configure this?

**Comment by jlengstorf** [comment]
@davidosomething this isn't something Gatsby allows to be configured, and you don't need to publish `.cache` — it's a build artifact, but not used on the built site

can you say a little more about what you're trying to accomplish? thanks!

**Comment by davidosomething** [comment]
sorry the issue was this:
i had the publish directory set in netlify via web:
![image](https://user-images.githubusercontent.com/609213/80161177-866ef600-859d-11ea-9219-bbbc62f0aae3.png)

but not in my `netlify.toml`. it MUST be in netlify.toml

```
[build]
  publish = "public"
```

to correctly receive the correct PUBLISH_DIR env var

**Comment by jlengstorf** [comment]
ah, great — this is a good note

thanks for following up!
