### ISSUE TITLE
Wrong `PUBLISH_DIR`

### ISSUE THREAD

**Issue by ehmicky** [jlengstorf/netlify-plugin-gatsby-cache#23]
Many [production builds are reporting](https://app.bugsnag.com/netlify/netlify-build/errors/5ea9b573e01a460018eb80da) the following error:

```
Cannot cache /opt/build/repo because it is the current directory (/opt/build/repo) or a parent directory
```

This comes from [this line of code](https://github.com/netlify/build/blob/8fe2d07d5e5a6dbfa6a8f6d47ec3403675db040a/packages/cache-utils/src/path.js#L32) in `utils.cache.restore()`.

This is turn indicates that either `PUBLISH_DIR` or `PUBLISH_DIR/../.cache` is the build/base directory. This seems to be due to a user misconfiguration, but considering the error happened frequently, I will investigate more.

If any users having this issue is reading this, feel free to chime in.

**Comment by jlengstorf** [comment]
@ehmicky is there a variable for the base dir? we could do something like
```js
if (PUBLISH_DIR === BASE_DIR) {
  failPlugin('your publish directory appears to be misconfigured')
}
```

**Comment by ehmicky** [comment]
The build directory is `process.cwd()` inside Build plugins.

The error message above is actually doing something similar but inside the `utils.cache` directly.

**Comment by jlengstorf** [comment]
this was fixed a while back and I forgot to close this

**Comment by ehmicky** [comment]
Thanks for updating @jlengstorf. The error has not been triggered in one month indeed :+1:
