### ISSUE TITLE
public.netlify.cache.json not found when clearing cache

### ISSUE THREAD

**Issue by slorber** [jlengstorf/netlify-plugin-gatsby-cache#24]
If I clear the cache, first run lead to this error. On retry it works fine.

![image](https://user-images.githubusercontent.com/749374/80824673-39170800-8bdf-11ea-9dfe-0ddc3028d0d2.png)

**Comment by slorber** [comment]
cc @ehmicky I guess :)

**Comment by jlengstorf** [comment]
this _should_ be fixed in the latest version. I'm going to close this, but please let me know if you're still seeing it

**Comment by ehmicky** [comment]
The error seems to be still happening, but this is a problem with the `cache` utility, so I open the following issue to track it: https://github.com/netlify/build/issues/1411
