### ISSUE TITLE
How does this interact with gatsby-plugin-netlify-cache?

### ISSUE THREAD

**Issue by guybowden** [jlengstorf/netlify-plugin-gatsby-cache#25]
I currently use this plugin on my site - 
https://www.gatsbyjs.org/packages/gatsby-plugin-netlify-cache/

It appears to do the same thing on paper - does this plugin differ somehow?

**Comment by jlengstorf** [comment]
they're more or less equivalent — this one uses Netlify's infrastructure and has fewer moving parts, so it's what I use and recommend, but I don't know that you need to change over if your setup is already working

if you're curious to see impact on build times, it could be interesting to test

I'm going to close this, but feel free to follow up with any additional questions!

**Comment by slorber** [comment]
The gatsby cache plugin is broken due to gatsby jobs v2 api. This plugin works better now, as it restores file way before in the lifecycle.

See https://github.com/axe312ger/gatsby-plugin-netlify-cache/issues/25#issuecomment-623491562

**Comment by robinmetral** [comment]
For whoever stumbles here and is interested: I've tested both approaches and while `gatsby-plugin-netlify-cache` brought my build time from 15min down to 10-12min, (tested prior to the Jobs v2 API, see comment above ☝️), this Netlify plugin brings the builds down to about 5min. Thank you @jlengstorf!
