### ISSUE TITLE
 Deploy failed due to an error in netlify-plugin-gatsby-cache plugin

### ISSUE THREAD

**Issue by stuut** [jlengstorf/netlify-plugin-gatsby-cache#28]
9:27:43 AM: │ Plugin "netlify-plugin-gatsby-cache" internal error │
9:27:43 AM: └─────────────────────────────────────────────────────┘
9:27:43 AM: ​
9:27:43 AM:   Error message
9:27:43 AM:   Error: This plugin is missing a "manifest.yml".
9:27:43 AM:   Please see the documentation at https://github.com/netlify/build#anatomy-of-a-plugin
9:27:43 AM: ​
9:27:43 AM:   Plugin details
9:27:43 AM:   Package:        netlify-plugin-gatsby-cache
9:27:43 AM:   Version:        0.2.1
9:27:43 AM:   Repository:     git+https://github.com/jlengstorf/netlify-plugin-gatsby-cache.git
9:27:43 AM:   npm link:       https://www.npmjs.com/package/netlify-plugin-gatsby-cache
9:27:43 AM:   Report issues:  https://github.com/jlengstorf/netlify-plugin-gatsby-cache/issues
9:27:43 AM: ​
9:27:43 AM:   Error location
9:27:43 AM:   While loading "netlify-plugin-gatsby-cache" from netlify.toml
9:27:43 AM:       at async Promise.all (index 0)
9:27:43 AM: ​
9:27:43 AM:   Resolved config
9:27:43 AM:   build:
9:27:43 AM:     command: gatsby build
9:27:43 AM:     publish: /opt/build/repo/public
9:27:43 AM:   plugins:
9:27:43 AM:     - origin: config
9:27:43 AM:       package: netlify-plugin-gatsby-cache

**Comment by ffdead** [comment]
This is breaking our build too 🙀

**Comment by jamie-endeavour** [comment]
Just witnessed this one myself this morning. I've temporarily disabled build plugins for the project in question.

**Comment by romainbessugesmeusy** [comment]
Breaking here too

**Comment by jondujaka** [comment]
Could it be related to ?
https://github.com/netlify/build/issues/1068
https://github.com/netlify/plugins/pull/45

**Comment by jlengstorf** [comment]
hey, everyone — can you please make sure you've updated to the latest version? 0.2.2 and 0.3.0 should be working as expected, so please let me know if it's still failing after you upgrade!

**Comment by jamie-endeavour** [comment]
That worked for me! Thanks @jlengstorf

**Comment by pierrenel** [comment]
@hitchcott ah, you have to go back into the plugins section on the Netlify website and hit install again, that sorted it out for me.

**Comment by hitchcott** [comment]
I removed and reinstalled the plugin in the netlify panel but that doesn't seem to fix it for new PR previews.

I'm having to manually clear the cache for each build right now.

**Comment by hiphotels** [comment]
How do you to specify the plugin version in the netlify.toml file?

This is the content of my netlify.toml file.
```
[build]
  publish = "public"
 
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
```

Netlify automatically install version 0.2.1
```
12:49:03 PM:   Plugin details
12:49:03 PM:   Package:        netlify-plugin-gatsby-cache
12:49:03 PM:   Version:        0.2.1
12:49:03 PM:   Repository:     git+https://github.com/jlengstorf/netlify-plugin-gatsby-cache.git
12:49:03 PM:   npm link:       https://www.npmjs.com/package/netlify-plugin-gatsby-cache
12:49:03 PM:   Report issues:  https://github.com/jlengstorf/netlify-plugin-gatsby-cache/issues
```

**Comment by hiphotels** [comment]
Please disregard my previous message.
I've solved this on Netlify clicking on Clear cache and redeploy site.

![screenshot](https://imgur.com/ZbQbVjN)

No need to specify a version on the netlify.toml file.

**Comment by jlengstorf** [comment]
is anyone still experiencing this issue after a "clear cache and deploy"?

we moved to stable release yesterday, which meant a lot of plugins got updated all at once — I _think_ the issue is now solved and this plugin will Just Work™, but please let me know if not!

I'm going to close for now, but add a comment if you hit this problem and we can reopen if necessary
