### ISSUE TITLE
build failing

### ISSUE THREAD

**Issue by shreyansh-zazz** [jlengstorf/netlify-plugin-gatsby-cache#30]
Following is the error I am getting while deploying with this plugin. I have added this plugin in `netlify.toml`

![image](https://user-images.githubusercontent.com/21006490/83524723-9f09ee80-a501-11ea-8765-df04e3b404ef.png)

**Comment by jlengstorf** [comment]
try running a "clear cache & deploy" — the latest version has the manifest and should work

see https://github.com/jlengstorf/netlify-plugin-gatsby-cache/issues/29 for details

thanks!

**Comment by shreyansh-zazz** [comment]
Yes, I upgraded the version and it worked.
