### ISSUE TITLE
auto-delete old cache or store /public/static instead of all public

### ISSUE THREAD

**Issue by PetroPavlenko** [jlengstorf/netlify-plugin-gatsby-cache#31]
This is close to  [other repo issue](https://github.com/axe312ger/gatsby-plugin-netlify-cache/issues/20)
But when I tried to delete page(build it locally or in netlify). I couldn't.
There was nothing about that in sitemap. But it was in `public/page-data`.

So, please use `public/static` instead of `public` folder

**Comment by probablyup** [comment]
I think there is a problem here though with the caching logic. I added this plugin to our Netlify setup and the cache grows at a rate of 0.5GB per week with 3-4 developers making a few PRs a day. The old builds don't seem to be pruned correctly.

**Comment by jlengstorf** [comment]
@probablyup it's hard to say without a full analysis, but this sounds like an upstream issue. all this plugin does is move the folders Gatsby creates, so any changes/additions come from Gatsby itself

**Comment by probablyup** [comment]
@jlengstorf yeah I think you're right, thanks for the explanation
