### ISSUE TITLE
update docs to propose GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES=true

### ISSUE THREAD

**Issue by PetroPavlenko** [jlengstorf/netlify-plugin-gatsby-cache#32]
## Reason
without GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES=true build doesn't delete old pages

**Comment by probablyup** [comment]
Doesn't delete with it either for us

**Comment by jlengstorf** [comment]
I think this might be an upstream Gatsby issue? if it's not removing old pages from the cache, that can't be fixed in this plugin, and I don't think we should require folks to enable experimental features

it looks like this might be the culprit? https://github.com/gatsbyjs/gatsby/issues/17402

**Comment by PetroPavlenko** [comment]
yep. We can stay with it
