### ISSUE TITLE
Post links not updated

### ISSUE THREAD

**Issue by rudotriton** [jlengstorf/netlify-plugin-gatsby-cache#35]
Hey,

I recently enabled this plugin on a Gatsby blog that I maintain. However, I was recently informed that blog posts don't show a link at the bottom of the page to newer posts anymore. If a new post is published this would link to the previous post and the previous post should update to include a link to the newest one, which it doesn't.

Is there something for cases like these, or does the previous post need to be changed every time for it to not match with the cached version so it gets rebuilt?

thanks

**Comment by jlengstorf** [comment]
@rudotriton this plugin doesn't affect how Gatsby builds; it only keeps the cache around the same way it persists for local builds

does this happen on your local builds with `gatsby build`?

**Comment by rudotriton** [comment]
You are right, it's a `gatsby build` peculiarity. I've never built it locally so I wasn't aware it would act this way when a cache is present.
