### ISSUE TITLE
Plugin "netlify-plugin-gatsby-cache" internal error

### ISSUE THREAD

**Issue by saillin** [jlengstorf/netlify-plugin-gatsby-cache#36]
`11:39:38 PM：构建准备开始
11:39:40 PM：构建映像版本：3031d4c9e432fd7016f6279fc9ad706f9205d845
11:39:40 PM：构建图像标记：v3.3.17
11:39:40 PM：buildbot版本：1f35b3abd6e2bf5230d8edf68072840fdec1513f
11:39:40 PM：获取缓存的依赖项
11:39:40 PM：开始下载24.2MB的缓存
11:39:40 PM：225.743114ms完成下载缓存
11:39:40 PM：开始提取缓存
11:39:40 PM：在265.676305ms中完成提取缓存
11:39:40 PM：499.480418ms完成获取缓存
11:39:40 PM：开始准备构建仓库
11:39:41 PM：准备Git参考refs / heads / master
11:39:42 PM：开始构建脚本
11:39:42 PM：安装依赖项
11:39:42 PM：Python版本设置为2.7
11:39:43 PM：v12.18.0已安装。
11:39:44 PM：现在使用节点v12.18.0（npm v6.14.4）
11:39:44 PM：开始还原缓存的构建插件
11:39:44 PM：完成还原缓存的构建插件
11:39:44 PM：尝试使用Ruby 2.7.1版，从环境中读取
11:39:45 PM：使用ruby版本2.7.1
11:39:46 PM：使用PHP 5.6
11:39:46 PM：5.2已安装。
11:39:46 PM：使用Swift版本5.2
11:39:46 PM：开始还原缓存的go缓存
11:39:46 PM：完成还原缓存的go缓存
11:39:46 PM：go版本go1.14.4 linux / amd64
11:39:46 PM：go版本go1.14.4 linux / amd64
11:39:46 PM：安装缺少的命令
11:39:46 PM：验证运行目录
晚上11:39:47：
11:39:47 PM：┌──────────────┐
11:39:47 PM：│Netlify构建│
11:39:47 PM：└──────────────┘
晚上11:39:47：
11:39:47 PM：❯版本
11:39:47 PM：@ netlify /内部版本2.0.10
晚上11:39:47：
11:39:47 PM：❯旗帜
11:39:47 PM：deployId：5ef4c539418978000837693c
11:39:47 PM：模式：buildbot
晚上11:39:47：
11:39:47 PM：❯当前目录
11:39:47 PM：/ opt / build / repo
晚上11:39:47：
11:39:47 PM：❯配置文件
11:39:47 PM：未定义配置文件：使用默认值。
晚上11:39:47：
11:39:47 PM：❯内容
11:39:47 PM：生产
晚上11:39:47：
11:39:47 PM：❯正在加载插件
11:39:47 PM：-Netlify应用中的netlify-plugin-a11y @ 0.0.12
11:39:47 PM：-Netlify应用中的netlify-plugin-amp-server-side-rendering @ 1.0.2
11:39:47 PM：- 来自Netlify应用的netlify-plugin-gatsby-cache @ 0.3.0
11:39:47 PM：- 来自Netlify应用程序的netlify-plugin-html-validate @ 0.1.1
11:39:47 PM：- 来自Netlify应用的netlify-plugin-image-optim @ 0.3.0
11:39:47 PM：- 来自Netlify应用程序的netlify-plugin-minify-html @ 0.2.3
晚上11:39:48：
11:39:48 PM：┌──────────────────────────────── ────────────┐
11:39:48 PM：│1.来自netlify-plugin-gatsby-cache的onPreBuild命令│
11:39:48 PM：└──────────────────────────────── ────────────┘
晚上11:39:48：
晚上11:39:49：
11:39:49 PM：┌──────────────────────────────── ──────────┐
11:39:49 PM：│插件“ netlify-plugin-gatsby-cache”内部错误│
11:39:49 PM：└──────────────────────────────── ──────────┘
晚上11:39:49：
11:39:49 PM：    错误消息
11:39:49 PM：错误：无法缓存/ opt / build / repo，因为它是当前目录（/ opt / build / repo）或父目录
晚上11:39:49：
11:39:49 PM：    插件详细信息
11:39:49 PM：包裹：netlify-plugin-gatsby-cache
11:39:49 PM：版本：0.3.0
11:39:49 PM：信息库：git + https：//github.com/jlengstorf/netlify-plugin-gatsby-cache.git
11:39:49 PM：npm链接：https://www.npmjs.com/package/netlify-plugin-gatsby-cache
11:39:49 PM：报告问题：https://github.com/jlengstorf/netlify-plugin-gatsby-cache/issues
晚上11:39:49：
11:39:49 PM：    错误位置
11:39:49 PM：来自Netlify应用程序的“ netlify-plugin-gatsby-cache”中的“ onPreBuild”事件
11:39:49 PM：在checkSrcPath（/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/cache-utils/src/ path.js：32：11）
11:39:49 PM：在getSrcPath（/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/cache-utils/src/ path.js：18：3）
11:39:49 PM：在parsePath（/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/cache-utils/src/ path.js：9：19）
11:39:49 PM：在restoreOne（/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/cache-utils/src/ main.js：34：40）
晚上11:39:49：在/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/cache-utils/src/main下。 js：81：55
11:39:49 PM：在Array.map（<anonymous>）
11:39:49 PM：在allowMany（/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/cache-utils/src/ main.js：81：43）
11:39:49 PM：在Object.restore（/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/cache-utils/ src / main.js：94：32）
11:39:49 PM：在onPreBuild（/opt/buildhome/.netlify-build-plugins/node_modules/netlify-plugin-gatsby-cache/index.js:12:27）
11:39:49 PM：在Object.run（/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/child/run.js ：15：9）
晚上11:39:49：
11:39:49 PM：    已解决配置
11:39:49 PM：建立：
11:39:49 PM：发布：/ opt / build / repo
晚上11:39:49：插件：
11:39:49 PM：-输入：{}
11:39:49 PM：来源：ui
11:39:49 PM：包裹：netlify-plugin-a11y
11:39:49 PM：-输入：{}
11:39:49 PM：来源：ui
11:39:49 PM：包裹：netlify-plugin-amp-server-side-rendering
11:39:49 PM：-输入：{}
11:39:49 PM：来源：ui
11:39:49 PM：包裹：netlify-plugin-gatsby-cache
11:39:49 PM：-输入：{}
11:39:49 PM：来源：ui
11:39:49 PM：包裹：netlify-plugin-html-validate
11:39:49 PM：-输入：{}
11:39:49 PM：来源：ui
11:39:49 PM：包裹：netlify-plugin-image-optim
11:39:49 PM：-输入：{}
11:39:49 PM：来源：ui
11:39:49 PM：包裹：netlify-plugin-minify-html
11:39:49 PM：缓存工件
11:39:49 PM：开始保存构建插件
11:39:49 PM：完成保存构建插件
11:39:49 PM：开始保存点子缓存
11:39:55 PM：完成保存点子缓存
11:39:55 PM：开始保存emacs桶依赖关系
11:39:55 PM：完成保存emacs桶依赖关系
11:39:55 PM: Started saving maven dependencies
11:39:55 PM: Finished saving maven dependencies
11:39:55 PM: Started saving boot dependencies
11:39:55 PM: Finished saving boot dependencies
11:39:55 PM: Started saving go dependencies
11:39:55 PM: Finished saving go dependencies
11:39:58 PM: Error running command: Build script returned non-zero exit code: 1
11:39:58 PM: Failing build: Failed to build site
11:39:58 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1
11:39:58 PM: Finished processing build request in 18.849272902s`

**Comment by jlengstorf** [comment]
please make sure your `publish` directory is set to `public` — Gatsby requires the `public` directory to be set or the site won't be published properly
