### ISSUE TITLE
Multiple Netlify CI builds fail

### ISSUE THREAD

**Issue by calebfaruki** [jlengstorf/netlify-plugin-gatsby-cache#38]
When pushing new changes to my deploy preview branch with incremental builds enabled, there are issues with the GatsbyJS graphQL static queries that does not happen when testing the production build locally.

I've confirmed that this issue does not happen when I clear the cache and redeploy from the deployment UI.

https://app.netlify.com/sites/leatherspa/deploys/5f0a288c08760800082f6c81
https://app.netlify.com/sites/leatherspa/deploys/5f0a0515a3a14200083346ea
https://app.netlify.com/sites/leatherspa/deploys/5f0a07501933c2c3599d7363

Here are the following builds that failed. There is a cache hit as expected and the failures are symptomatic of the underlying content changes I made between the builds. Perhaps the cache invalidation is not validating whether markdown content has changed?

**Comment by jlengstorf** [comment]
@ehmicky do you any insight into what might be happening here?

**Comment by ehmicky** [comment]
I am not quite sure, but I am wondering whether this might not be related to this plugin.
@calebfaruki If you remove this plugin, is your build succeeding?

**Comment by jlengstorf** [comment]
I'm going to close this issue since it's been quiet for a while. if anyone else is hitting this bug, please let us know!
