### ISSUE TITLE
Error in netlify build after enabling plugin

### ISSUE THREAD

**Issue by badiuoanaalexandra** [jlengstorf/netlify-plugin-gatsby-cache#40]
/opt/build/repo/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
 throw ex;
 ^
Error: Callback was already called.
at throwError (/opt/build/repo/node_modules/neo-async/async.js:16:11)
at /opt/build/repo/node_modules/neo-async/async.js:2818:7
at processTicksAndRejections (internal/process/task_queues.js:79:11)
<img width="1132" alt="Screenshot 2020-07-25 at 21 40 55" src="https://user-images.githubusercontent.com/4539422/88463986-b17c2500-cebf-11ea-9d6e-528d73cd12b2.png">

**Comment by jlengstorf** [comment]
hi, @badiuoanaalexandra — does the build succeed if you disable the plugin? the error shown here is from code that's not part of this plugin, which makes me wonder if something has happened with Gatsby itself or this `yoga-layout-prebuilt` module

**Comment by badiuoanaalexandra** [comment]
Hi! Yes, build is successful when disabling the plugin.

**Comment by jlengstorf** [comment]
@badiuoanaalexandra could you please share the links to the Netlify build logs for the failing build with the plugin and the passing build with it uninstalled? we'll have to look a little deeper to figure out what's going on here

thanks!

**Comment by badiuoanaalexandra** [comment]
Actually after enabling it again it started to work without problems. I haven't changed any libraries in my code or anything like that, so don't know why it wasn't working previously. 

Here are the links with the builds from that day that have failed, however since it's now working I can mark this as solved.
https://app.netlify.com/sites/upbeat-joliot-da042e/deploys/5f1c7bc0b5e249af3b753b51
https://app.netlify.com/sites/upbeat-joliot-da042e/deploys/5f1c7815326a120007581a9e

Here is the build that succeeded after removing plugin:
https://app.netlify.com/sites/upbeat-joliot-da042e/deploys/5f1c7de2bc6a8766455e0ece

**Comment by jlengstorf** [comment]
thanks for the follow-up! if you spot anything else, please let us know!
