### ISSUE TITLE
Does the UI installing process require any other configuration?

### ISSUE THREAD

**Issue by lucis** [jlengstorf/netlify-plugin-gatsby-cache#42]
Hey @jlengstorf, I'm not sure I'm getting the setup instructions correctly.

![image](https://user-images.githubusercontent.com/18706156/94919374-c4e0d900-048a-11eb-831f-c943dbfd2c22.png)

Despite using `If you don’t want to use the UI-based installation`, it later says that `this must be set in your netlify.toml in the [build] section`. I'm not sure if automatically installing it on Netlify UI is enough, and also I can't know for sure that my plugin is working.

If you point something that could be improved on the documentation, I'd be happy to contribute :)

Thanks

**Comment by jlengstorf** [comment]
ah, yep — these instructions are intended only if you're _not_ using the UI

this would be a wonderful clarification if you've got the time to contribute! thanks!

**Comment by lucis** [comment]
@jlengstorf #43 ✨

**Comment by bturner-cfn** [comment]
@jlengstorf, are you suggesting that the cache can break or behave inconsistently if you configure from UI & via project's code?

**Comment by jlengstorf** [comment]
@bturner-cfn not at all — they'll behave the same way, but only one or the other is required

thanks so much for the PR @lucis!
