### ISSUE TITLE
Working with Strapi as CMS ? 

### ISSUE THREAD

**Issue by impsdc** [jlengstorf/netlify-plugin-gatsby-cache#45]
I was wondering if incremental build was working with strapi as cms. My app is building fine but on data change from strapi nothing happen in log ...

**Comment by jlengstorf** [comment]
@impsdc for Strapi data changes to rebuild the site, a webhook is required

Maxime from the Strapi team wrote up a guide on [setting up Netlify build hooks with Strapi](https://www.netlify.com/blog/2020/08/11/deploy-a-strapi-and-react-blog-on-netlify/#automatically-redeploy-to-netlify-when-content-is-changed-in-strapi) that covers the required steps

I'm going to close this, but feel free to hit me up here or [on Twitter](https://twitter.com/jlengstorf) if you have additional questions!
