### ISSUE TITLE
Can’t uninstall plugin in netlify web interface

### ISSUE THREAD

**Issue by felixbuchholz** [jlengstorf/netlify-plugin-gatsby-cache#49]
The uninstall option is not shown in the option panel of the plugin. The plugin still gets triggered in build processes, and we sometimes have issues with our CMS. 

Is there a way to uninstall the plugin differently? Thanks in advance!

**Comment by jlengstorf** [comment]
is the plugin installed in your `netlify.toml`?

if not, this sounds like a Netlify bug — you can [post in the forums](https://answers.netlify.com/) and they can dig into why the uninstall button isn't available

thanks!
