### ISSUE TITLE
Stored cache is ignored on build

### ISSUE THREAD

**Issue by qubis741** [jlengstorf/netlify-plugin-gatsby-cache#53]
Hello there,
I was using this cool plugin for a long time without any problems, but on 15.3.2021 it suddenly stopped to retrieve stored cache. I though it might be because I was running on gatsby v2, so I have updated all related libs to work on gatsby v3, but still no luck. I have also tried to clear cache. Plugin was installed via Netlify UI, I have also tried installing it via  `netlify.toml` and throught package. After build is says that cache are stored but on next one, it says it havent found any. Here is my log. 

Here is my deploy log (its private repo so cant give you link):
2:24:30 PM: Build ready to start
2:24:32 PM: build-image version: be42e453d6c8f171cc2f654acc29c0a8b60e6d93
2:24:32 PM: build-image tag: v3.7.1
2:24:32 PM: buildbot version: 449a896d650f66a48d6924703527235917156153
2:24:32 PM: Fetching cached dependencies
2:24:33 PM: Starting to download cache of 381.3MB
2:24:36 PM: Finished downloading cache in 3.783328282s
2:24:36 PM: Starting to extract cache
2:24:51 PM: Finished extracting cache in 15.215106742s
2:24:52 PM: Finished fetching cache in 19.13159458s
2:24:52 PM: Starting to prepare the repo for build
2:24:52 PM: Preparing Git Reference refs/heads/master
2:24:54 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: ‘public’ versus ‘public/’ in the Netlify UI
2:24:55 PM: Starting build script
2:24:55 PM: Installing dependencies
2:24:55 PM: Python version set to 2.7
2:24:55 PM: Started restoring cached node version
2:24:59 PM: Finished restoring cached node version
2:24:59 PM: Downloading and installing node v12.13.0…
2:25:00 PM: Downloading https://nodejs.org/dist/v12.13.0/node-v12.13.0-linux-x64.tar.xz…
2:25:00 PM: Computing checksum with sha256sum
2:25:00 PM: Checksums matched!
2:25:03 PM: Now using node v12.13.0 (npm v6.12.0)
2:25:03 PM: Started restoring cached build plugins
2:25:03 PM: Finished restoring cached build plugins
2:25:03 PM: Attempting ruby version 2.6.2, read from environment
2:25:04 PM: Using ruby version 2.6.2
2:25:05 PM: Using PHP version 5.6
2:25:05 PM: Started restoring cached node modules
2:25:05 PM: Finished restoring cached node modules
2:25:05 PM: Installing NPM modules using NPM version 6.12.0
2:25:51 PM: > sharp@0.27.2 install /opt/build/repo/node_modules/sharp
2:25:51 PM: > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
2:25:52 PM: info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.5/libvips-8.10.5-linux-x64.tar.br
2:25:55 PM: > core-js@3.10.0 postinstall /opt/build/repo/node_modules/core-js
2:25:55 PM: > node -e “try{require(’./postinstall’)}catch(e){}”
2:25:55 PM: > core-js-pure@3.10.0 postinstall /opt/build/repo/node_modules/core-js-pure
2:25:55 PM: > node -e “try{require(’./postinstall’)}catch(e){}”
2:25:55 PM: > gatsby-telemetry@1.10.1 postinstall /opt/build/repo/node_modules/gatsby-telemetry
2:25:55 PM: > node src/postinstall.js || true
2:25:55 PM: > gatsby-cli@2.19.2 postinstall /opt/build/repo/node_modules/gatsby/node_modules/gatsby-cli
2:25:55 PM: > node scripts/postinstall.js
2:25:55 PM: > gatsby@2.32.11 postinstall /opt/build/repo/node_modules/gatsby
2:25:55 PM: > node scripts/postinstall.js
2:25:58 PM: npm WARN risoto-shop@1.0.0 No repository field.
2:25:58 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
2:25:58 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {“os”:“darwin”,“arch”:“any”} (current: {“os”:“linux”,“arch”:“x64”})
2:25:58 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
2:25:58 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {“os”:“darwin”,“arch”:“any”} (current: {“os”:“linux”,“arch”:“x64”})
2:25:58 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
2:25:58 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {“os”:“darwin”,“arch”:“any”} (current: {“os”:“linux”,“arch”:“x64”})
2:25:58 PM: added 625 packages from 187 contributors, removed 1076 packages, updated 554 packages and audited 2748 packages in 52.471s
2:25:58 PM: found 4 vulnerabilities (3 low, 1 high)
2:25:58 PM: run npm audit fix to fix them, or npm audit for details
2:25:58 PM: NPM modules installed
2:25:58 PM: Started restoring cached go cache
2:26:00 PM: Finished restoring cached go cache
2:26:00 PM: Installing Go version 1.12
2:26:00 PM: unset GOOS;
2:26:00 PM: unset GOARCH;
2:26:00 PM: export GOROOT=’/opt/buildhome/.gimme_cache/versions/go1.12.linux.amd64’;
2:26:00 PM: export PATH="/opt/buildhome/.gimme_cache/versions/go1.12.linux.amd64/bin:{PATH}"; 2:26:00 PM: go version >&2; 2:26:00 PM: export GIMME_ENV='/opt/buildhome/.gimme_cache/env/go1.12.linux.amd64.env'; 2:26:00 PM: go version go1.12 linux/amd64 2:26:00 PM: Installing missing commands 2:26:00 PM: Verify run directory 2:26:02 PM: ​ 2:26:02 PM: ──────────────────────────────────────────────────────────────── 2:26:02 PM: Netlify Build 2:26:02 PM: ──────────────────────────────────────────────────────────────── 2:26:02 PM: ​ 2:26:02 PM: ❯ Version 2:26:02 PM: @netlify/build 10.2.3 2:26:02 PM: ​ 2:26:02 PM: ❯ Flags 2:26:02 PM: deployId: 606da47e604a3c0007fa2999 2:26:02 PM: ​ 2:26:02 PM: ❯ Current directory 2:26:02 PM: /opt/build/repo 2:26:02 PM: ​ 2:26:02 PM: ❯ Config file 2:26:02 PM: /opt/build/repo/netlify.toml 2:26:02 PM: ​ 2:26:02 PM: ❯ Context 2:26:02 PM: production 2:26:02 PM: ​ 2:26:02 PM: ❯ Loading plugins 2:26:02 PM: - netlify-plugin-gatsby-cache@0.3.2 from netlify.toml and package.json 2:26:02 PM: ​ 2:26:02 PM: ──────────────────────────────────────────────────────────────── 2:26:02 PM: 1. onPreBuild command from netlify-plugin-gatsby-cache 2:26:02 PM: ──────────────────────────────────────────────────────────────── 2:26:02 PM: ​ 2:26:02 PM: No Gatsby cache found. Building fresh. 2:26:02 PM: ​ 2:26:02 PM: (netlify-plugin-gatsby-cache onPreBuild completed in 209ms) 2:26:02 PM: ​ 2:26:02 PM: ──────────────────────────────────────────────────────────────── 2:26:02 PM: 2. Build command from Netlify app 2:26:02 PM: ──────────────────────────────────────────────────────────────── 2:26:02 PM: ​ 2:26:02 PM: gatsby build
2:26:05 PM: success open and validate gatsby-configs - 0.067s
2:26:06 PM: success load plugins - 0.807s
2:26:06 PM: success onPreInit - 0.138s
2:26:06 PM: success delete html and css files from previous builds - 0.004s
2:26:06 PM: success initialize cache - 0.010s
2:26:06 PM: success copy gatsby files - 0.043s
2:26:06 PM: success onPreBootstrap - 0.016s
2:26:06 PM: success createSchemaCustomization - 0.007s
2:26:06 PM:
2:26:06 PM: gatsby-source-shopify/risoto-shop starting to fetch data from Shopify
2:26:06 PM:
2:26:06 PM: gatsby-source-shopify/risoto-shop fetched and processed Collection nodes: 186.080ms
2:26:06 PM:
2:26:06 PM: gatsby-source-shopify/risoto-shop fetched and processed Shop nodes: 178.341ms
2:26:06 PM:
2:26:06 PM: gatsby-source-shopify/risoto-shop fetched and processed ShopPolicy nodes: 182.796ms
2:26:06 PM:
2:26:06 PM: gatsby-source-shopify/risoto-shop fetched and processed Blog nodes: 195.480ms
2:26:07 PM:
2:26:07 PM: gatsby-source-shopify/risoto-shop fetched and processed Page nodes: 321.444ms
2:26:07 PM:
2:26:07 PM: gatsby-source-shopify/risoto-shop fetched and processed Article nodes: 417.496ms
2:26:12 PM: success Downloading remote files - 5.722s - 120/120 20.97/s
2:26:12 PM:
2:26:12 PM: gatsby-source-shopify/risoto-shop fetched and processed Product nodes: 5978.301ms
2:26:12 PM:
2:26:12 PM: gatsby-source-shopify/risoto-shop finished fetching data from Shopify: 5972.184ms
2:26:12 PM: success Checking for changed pages - 0.000s
2:26:12 PM: success source and transform nodes - 6.108s
2:26:13 PM: success building schema - 0.596s
2:26:13 PM: info Total nodes: 444, SitePage nodes: 36 (use --verbose for breakdown)
2:26:13 PM: success createPages - 0.054s
2:26:13 PM: success Checking for changed pages - 0.000s
2:26:13 PM: success createPagesStatefully - 0.105s
2:26:13 PM: success update schema - 0.036s
2:26:13 PM: success onPreExtractQueries - 0.001s
2:26:14 PM: success extract queries from components - 0.757s
2:26:14 PM: success write out redirect data - 0.002s
2:26:14 PM: warning The icon(static/favicon.png) you provided to ‘gatsby-plugin-manifest’ is not square.
2:26:14 PM: The icons we generate will be square and for the best results we recommend you provide a square icon.
2:26:14 PM: success Build manifest and related icons - 0.328s
2:26:14 PM: success onPostBootstrap - 0.331s
2:26:14 PM: info bootstrap finished - 11.927s
2:26:29 PM: warning Query takes too long:
2:26:29 PM: File path: /opt/build/repo/src/components/Cart/CartThumbnail.js
2:26:29 PM: warning Query takes too long:
2:26:29 PM: File path: /opt/build/repo/src/components/Product/ProductMainImage.js
2:26:29 PM: warning Query takes too long:
2:26:29 PM: File path: /opt/build/repo/src/components/ProductListing/ProductListing.js
2:26:29 PM: warning Query takes too long:
2:26:29 PM: File path: /opt/build/repo/src/components/shared/SiteMetadata.js
2:27:35 PM: success run static queries - 81.291s - 4/4 0.05/s
2:28:07 PM: success run page queries - 31.795s - 45/45 1.42/s
2:28:07 PM: success write out requires - 0.088s
2:31:44 PM: success Building production JavaScript and CSS bundles - 216.687s
2:31:46 PM: success Rewriting compilation hashes - 0.770s
2:49:42 PM: success Building HTML renderer - 9.519s
2:49:43 PM: success Building static HTML for pages - 0.730s - 45/45 61.65/s
2:49:43 PM: success Generating image thumbnails - 1408.442s - 2360/2360 1.68/s
2:49:43 PM: success onPostBuild - 0.034s
2:49:43 PM: info Done building in 1420.574906185 sec
2:49:43 PM: ​
2:49:43 PM: (build.command completed in 23m 40.9s)
2:49:43 PM: ​
2:49:43 PM: ────────────────────────────────────────────────────────────────
2:49:43 PM: 3. onPostBuild command from netlify-plugin-gatsby-cache
2:49:43 PM: ────────────────────────────────────────────────────────────────
2:49:43 PM: ​
2:49:48 PM: Stored the Gatsby cache to speed up future builds.
2:49:48 PM: ​
2:49:48 PM: (netlify-plugin-gatsby-cache onPostBuild completed in 5.2s)
2:49:48 PM: ​
2:49:48 PM: ────────────────────────────────────────────────────────────────
2:49:48 PM: 4. Deploy site
2:49:48 PM: ────────────────────────────────────────────────────────────────
2:49:48 PM: ​
2:49:48 PM: Starting to deploy site from ‘public’
2:49:49 PM: Creating deploy tree asynchronously
2:49:49 PM: Creating deploy upload records
2:49:52 PM: 58 new files to upload
2:49:52 PM: 0 new functions to upload
2:49:52 PM: Site deploy was successfully initiated
2:49:52 PM: ​
2:49:52 PM: (Deploy site completed in 4.1s)
2:49:53 PM: ​
2:49:53 PM: ────────────────────────────────────────────────────────────────
2:49:53 PM: Netlify Build Complete
2:49:53 PM: ────────────────────────────────────────────────────────────────
2:49:53 PM: ​
2:49:53 PM: (Netlify Build completed in 23m 51s)
2:49:53 PM: Execution timed out after 24m58.147551752s
2:49:53 PM: Error running command: Command did not finish within the time limit
2:49:53 PM: Failing build: Failed to build site
2:49:53 PM: Failed during stage ‘building site’: Command did not finish within the time limit
2:49:53 PM: Finished processing build request in 25m20.708055275s
2:49:59 PM: Starting post processing
2:49:59 PM: Post processing - HTML
2:50:03 PM: Post processing - header rules
2:50:03 PM: Post processing - redirect rules
2:50:03 PM: Post processing done
2:50:03 PM: Site is live

**Comment by qubis741** [comment]
So I have found what is wrong. As you can see in bottom of log, it says that Command did not finish within the time limit. It is because Netlify Build time limit is 15minutes. Site got deployed but cache was not stored, even if it says its stored. So solution is to reduce build time temporary (in my case it was removing some products from sales channel), netlify saves that part to cache and continually get back everything as it was, since next build will use data from cache. Maybe you can add some info to README that build needs to be finished under 15minutes to have cache saved.

**Comment by jdortegar** [comment]
Same issue here, cache is not founden in each build, here are the logs
```
2:05:11 PM: Build ready to start
2:05:13 PM: build-image version: be42e453d6c8f171cc2f654acc29c0a8b60e6d93
2:05:13 PM: build-image tag: v3.7.1
2:05:13 PM: buildbot version: f8ec74861753a79c1e9b582ecf018c0cd8e5c53d
2:05:13 PM: Fetching cached dependencies
2:05:13 PM: Failed to fetch cache, continuing with build
2:05:13 PM: Starting to prepare the repo for build
2:05:14 PM: No cached dependencies found. Cloning fresh repo
2:05:14 PM: git clone https://github.com/LiveOuter/webstore
2:05:17 PM: Preparing Git Reference pull/331/head
2:05:21 PM: Starting build script
2:05:21 PM: Installing dependencies
2:05:21 PM: Python version set to 2.7
2:05:22 PM: Attempting node version '12' from .nvmrc
2:05:23 PM: Downloading and installing node v12.22.1...
2:05:23 PM: Downloading https://nodejs.org/dist/v12.22.1/node-v12.22.1-linux-x64.tar.xz...
2:05:23 PM: Computing checksum with sha256sum
2:05:23 PM: Checksums matched!
2:05:26 PM: Now using node v12.22.1 (npm v6.14.12)
2:05:26 PM: Started restoring cached build plugins
2:05:26 PM: Finished restoring cached build plugins
2:05:26 PM: Attempting ruby version 2.7.1, read from environment
2:05:28 PM: Using ruby version 2.7.1
2:05:28 PM: Using PHP version 5.6
2:05:28 PM: Started restoring cached node modules
2:05:28 PM: Finished restoring cached node modules
2:05:28 PM: Installing NPM modules using NPM version 6.14.12
2:07:13 PM: > sharp@0.27.2 install /opt/build/repo/node_modules/sharp
2:07:13 PM: > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
2:07:14 PM: info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.5/libvips-8.10.5-linux-x64.tar.br
2:07:17 PM: > husky@4.3.0 install /opt/build/repo/node_modules/husky
2:07:17 PM: > node husky install
2:07:17 PM: husky > Setting up git hooks
2:07:17 PM: CI detected, skipping Git hooks installation.
2:07:17 PM: husky > Done
2:07:17 PM: > node-sass@4.14.1 install /opt/build/repo/node_modules/node-sass
2:07:17 PM: > node scripts/install.js
2:07:18 PM: Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-72_binding.node
2:07:18 PM: Download complete
2:07:18 PM: Binary saved to /opt/build/repo/node_modules/node-sass/vendor/linux-x64-72/binding.node
2:07:18 PM: Caching binary to /opt/buildhome/.npm/node-sass/4.14.1/linux-x64-72_binding.node
2:07:19 PM: > core-js@2.6.11 postinstall /opt/build/repo/node_modules/babel-plugin-espower/node_modules/core-js
2:07:19 PM: > node -e "try{require('./postinstall')}catch(e){}"
2:07:19 PM: > core-js@2.6.11 postinstall /opt/build/repo/node_modules/babel-runtime/node_modules/core-js
2:07:19 PM: > node -e "try{require('./postinstall')}catch(e){}"
2:07:20 PM: > core-js@2.6.11 postinstall /opt/build/repo/node_modules/call-matcher/node_modules/core-js
2:07:20 PM: > node -e "try{require('./postinstall')}catch(e){}"
2:07:20 PM: > core-js@3.6.5 postinstall /opt/build/repo/node_modules/core-js
2:07:20 PM: > node -e "try{require('./postinstall')}catch(e){}"
2:07:20 PM: > core-js-pure@3.9.1 postinstall /opt/build/repo/node_modules/core-js-pure
2:07:20 PM: > node -e "try{require('./postinstall')}catch(e){}"
2:07:20 PM: > core-js@2.6.11 postinstall /opt/build/repo/node_modules/empower-core/node_modules/core-js
2:07:20 PM: > node -e "try{require('./postinstall')}catch(e){}"
2:07:20 PM: > core-js@2.6.11 postinstall /opt/build/repo/node_modules/espurify/node_modules/core-js
2:07:20 PM: > node -e "try{require('./postinstall')}catch(e){}"
2:07:24 PM: > gatsby-telemetry@2.0.0 postinstall /opt/build/repo/node_modules/gatsby-telemetry
2:07:24 PM: > node src/postinstall.js || true
2:07:24 PM: > mozjpeg@7.0.0 postinstall /opt/build/repo/node_modules/mozjpeg
2:07:24 PM: > node lib/install.js
2:07:25 PM:   ✔ mozjpeg pre-build test passed successfully
2:07:25 PM: > pngquant-bin@6.0.0 postinstall /opt/build/repo/node_modules/pngquant-bin
2:07:25 PM: > node lib/install.js
2:07:25 PM:   ✔ pngquant pre-build test passed successfully
2:07:25 PM: > gatsby-cli@3.0.0 postinstall /opt/build/repo/node_modules/gatsby/node_modules/gatsby-cli
2:07:25 PM: > node scripts/postinstall.js
2:07:26 PM: > gatsby@3.0.4 postinstall /opt/build/repo/node_modules/gatsby
2:07:26 PM: > node scripts/postinstall.js
2:07:26 PM: > husky@4.3.0 postinstall /opt/build/repo/node_modules/husky
2:07:26 PM: > opencollective-postinstall || exit 0
2:07:26 PM: > node-sass@4.14.1 postinstall /opt/build/repo/node_modules/node-sass
2:07:26 PM: > node scripts/build.js
2:07:26 PM: Binary found at /opt/build/repo/node_modules/node-sass/vendor/linux-x64-72/binding.node
2:07:26 PM: Testing binary
2:07:27 PM: Binary is fine
2:07:33 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
2:07:33 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2:07:33 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
2:07:33 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2:07:33 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/gatsby-plugin-page-creator/node_modules/fsevents):
2:07:33 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2:07:33 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/gatsby-plugin-image/node_modules/fsevents):
2:07:33 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2:07:33 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/gatsby-page-utils/node_modules/fsevents):
2:07:33 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2:07:33 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.2.1 (node_modules/fsevents):
2:07:33 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.2.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2:07:33 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/chokidar/node_modules/fsevents):
2:07:33 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2:07:33 PM: added 4168 packages from 1858 contributors and audited 4189 packages in 124.217s
2:07:39 PM: 309 packages are looking for funding
2:07:39 PM:   run `npm fund` for details
2:07:39 PM: found 1 high severity vulnerability
2:07:39 PM:   run `npm audit fix` to fix them, or `npm audit` for details
2:07:40 PM: NPM modules installed
2:07:40 PM: Started restoring cached go cache
2:07:40 PM: Finished restoring cached go cache
2:07:40 PM: go version go1.14.4 linux/amd64
2:07:40 PM: go version go1.14.4 linux/amd64
2:07:40 PM: Installing missing commands
2:07:40 PM: Verify run directory
2:07:42 PM: ​
2:07:42 PM: ────────────────────────────────────────────────────────────────
2:07:42 PM:   Netlify Build                                                 
2:07:42 PM: ────────────────────────────────────────────────────────────────
2:07:42 PM: ​
2:07:42 PM: ❯ Version
2:07:42 PM:   @netlify/build 10.2.7
2:07:42 PM: ​
2:07:42 PM: ❯ Flags
2:07:42 PM:   deployId: 60747dc7d49fda0007b68a64
2:07:42 PM: ​
2:07:42 PM: ❯ Current directory
2:07:42 PM:   /opt/build/repo
2:07:42 PM: ​
2:07:42 PM: ❯ Config file
2:07:42 PM:   /opt/build/repo/netlify.toml
2:07:42 PM: ​
2:07:42 PM: ❯ Context
2:07:42 PM:   deploy-preview
2:07:42 PM: ​
2:07:42 PM: ❯ Loading plugins
2:07:42 PM:    - netlify-plugin-gatsby-cache@0.3.2 from netlify.toml and package.json
2:07:42 PM: ​
2:07:42 PM: ────────────────────────────────────────────────────────────────
2:07:42 PM:   1. onPreBuild command from netlify-plugin-gatsby-cache        
2:07:42 PM: ────────────────────────────────────────────────────────────────
2:07:42 PM: ​
2:07:43 PM: No Gatsby cache found. Building fresh.
2:07:43 PM: ​
2:07:43 PM: (netlify-plugin-gatsby-cache onPreBuild completed in 279ms)
2:07:43 PM: ​
2:07:43 PM: ────────────────────────────────────────────────────────────────
2:07:43 PM:   2. Build command from Netlify app                             
2:07:43 PM: ────────────────────────────────────────────────────────────────
2:07:43 PM: ​
2:07:43 PM: $ npm run build
2:07:43 PM: > webstore@1.0.0 build /opt/build/repo
2:07:43 PM: > cross-env GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES=true gatsby build --log-pages
2:07:47 PM: info The following flags are active:
2:07:47 PM: - PRESERVE_WEBPACK_CACHE · (Umbrella Issue (https://gatsby.dev/cache-clearing-feedback)) · Don't delete webpack's cache when changing gatsby-node.js & gatsby-config.js files.
2:07:47 PM: - PRESERVE_FILE_DOWNLOAD_CACHE · (Umbrella Issue (https://gatsby.dev/cache-clearing-feedback)) · Don't delete the downloaded files cache when changing gatsby-node.js & gatsby-config.js files.
2:07:47 PM: - PARALLEL_SOURCING · EXPERIMENTAL · (Umbrella Issue (https://gatsby.dev/parallel-sourcing-feedback)) · Run all source plugins at the same time instead of serially. For sites with multiple source plugins, this can speedup sourcing and transforming considerably.
2:07:47 PM: There are 2 other flags available that you might be interested in:
2:07:47 PM: - FAST_DEV · Enable all experiments aimed at improving develop server start time
2:07:47 PM: - DEV_SSR · (Umbrella Issue (https://gatsby.dev/dev-ssr-feedback)) · Server Side Render (SSR) pages on full reloads during develop. Helps you detect SSR bugs and fix them without needing to do full builds.
2:07:47 PM: success open and validate gatsby-configs - 0.383s
2:07:49 PM: warning Plugin gatsby-plugin-next-seo is not compatible with your gatsby version 3.0.4 - It requires gatsby@^2
2:07:49 PM: success load plugins - 1.631s
2:07:49 PM: success onPreInit - 0.062s
2:07:49 PM: success initialize cache - 0.010s
2:07:49 PM: success copy gatsby files - 0.085s
2:07:49 PM: success onPreBootstrap - 0.025s
2:07:49 PM: success createSchemaCustomization - 0.044s
2:07:50 PM: info Starting to fetch data from Strapi - https://alameda-staging.herokuapp.com/products?_limit=1000
2:07:50 PM: info Starting to fetch data from Strapi - https://alameda-staging.herokuapp.com/catalogs?_limit=1000
2:07:53 PM: warning Calling "touchNode" with an object containing the nodeId is deprecated. Please pass the node directly to the function: touchNode(node) "touchNode" was called by gatsby-source-strapi
2:08:01 PM: success Fetched Strapi Data - 11.507s
2:08:01 PM: success Checking for changed pages - 0.000s
2:08:01 PM: success source and transform nodes - 11.666s
2:08:04 PM: success building schema - 2.671s
2:08:18 PM: info Total nodes: 1643, SitePage nodes: 403 (use --verbose for breakdown)
2:08:18 PM: success createPages - 14.627s
2:08:18 PM: success Checking for changed pages - 0.000s
2:08:19 PM: success createPagesStatefully - 0.216s
2:08:19 PM: success update schema - 0.289s
2:08:19 PM: success onPreExtractQueries - 0.001s
2:08:22 PM: success extract queries from components - 3.399s
2:08:22 PM: success write out redirect data - 0.002s
2:08:22 PM: success onPostBootstrap - 0.001s
2:08:22 PM: info bootstrap finished - 39.142s
2:08:24 PM: success run static queries - 1.331s - 6/6 4.51/s
2:10:25 PM: warning Query takes too long:
2:10:25 PM: File path: /opt/build/repo/src/templates/ProductDetails/ProductDetails.tsx
2:10:25 PM: URL path: /seating/the-armchair-five-piece/palisades-cream
2:10:25 PM: Context: {
2:10:25 PM:     "catalogSlug": "seating",
2:10:25 PM:     "enable": true,
2:10:25 PM:     "productId": "113",
2:10:25 PM:     "productSlug": "the-armchair-five-piece",
2:10:25 PM:     "variantSlug": "palisades-cream",
2:10:25 PM:     "sitemapDisabled": false
2:10:25 PM: }
2:19:21 PM: success run page queries - 657.843s - 425/425 0.65/s
2:19:22 PM: success write out requires - 0.101s
2:24:24 PM: success Building production JavaScript and CSS bundles - 301.850s
2:24:25 PM: success Rewriting compilation hashes - 0.003s
2:25:24 PM: success Building HTML renderer - 56.747s
2:25:24 PM: OUTER:::INFO Local storage is not ready
2:25:25 PM: OUTER:::INFO Local storage is not ready
2:25:25 PM: OUTER:::INFO Local storage is not ready
2:25:25 PM: OUTER:::INFO Local storage is not ready
2:25:41 PM: success Building static HTML for pages - 17.022s - 425/425 24.97/s
2:25:44 PM: success onPostBuild - 3.801s
2:25:45 PM: info Done building in 1081.422020817 sec
2:25:45 PM: info Built pages:
2:25:45 PM: Updated page: /privacy
2:25:45 PM: Updated page: /terms
2:25:45 PM: Updated page: /shipping-and-returns
2:25:45 PM: Updated page: /care-and-maintenance
2:25:45 PM: Updated page: /warranty
2:25:45 PM: Updated page: /products
2:25:45 PM: Updated page: /outdoor-rugs
2:25:45 PM: Updated page: /covers
2:25:45 PM: Updated page: /gifts
2:25:45 PM: Updated page: /accessories
2:25:45 PM: Updated page: /seating
2:25:45 PM: Updated page: /wicker
2:25:45 PM: Updated page: /teak
2:25:45 PM: Updated page: /sofas-and-sectionals
2:25:45 PM: Updated page: /chairs
2:25:45 PM: Updated page: /tables
2:25:45 PM: Updated page: /build
2:25:45 PM: Updated page: /outdoor-rugs/1188-eco-friendly-outdoor-rug-pebble-gray/5-by-8
2:25:45 PM: Updated page: /outdoor-rugs/1188-eco-friendly-outdoor-rug-pebble-gray/8-by-10
2:25:45 PM: Updated page: /outdoor-rugs/1188-eco-friendly-outdoor-rug-pebble-gray/9-by-12
2:25:45 PM: Updated page: /outdoor-rugs/1188-eco-friendly-outdoor-rug-seashell-gray/5-by-8
2:25:45 PM: Updated page: /outdoor-rugs/1188-eco-friendly-outdoor-rug-seashell-gray/8-by-10
2:25:45 PM: Updated page: /outdoor-rugs/1188-eco-friendly-outdoor-rug-seashell-gray/9-by-12
2:25:45 PM: Updated page: /outdoor-rugs/1188-outdoor-rug-sand-dune-beige/5-by-8
2:25:45 PM: Updated page: /outdoor-rugs/1188-outdoor-rug-sand-dune-beige/8-by-10
2:25:45 PM: Updated page: /outdoor-rugs/1188-outdoor-rug-sand-dune-beige/9-by-12
2:25:45 PM: Updated page: /covers/five-piece-outdoor-sofa-all-weather-cover
2:25:45 PM: Updated page: /covers/four-piece-outdoor-sofa-all-weather-cover
2:25:45 PM: Updated page: /404.html
2:25:45 PM: ​
2:25:45 PM: (build.command completed in 18m 2.2s)
2:25:45 PM: ​
2:25:45 PM: ────────────────────────────────────────────────────────────────
2:25:45 PM:   3. onPostBuild command from netlify-plugin-gatsby-cache       
2:25:45 PM: ────────────────────────────────────────────────────────────────
2:25:45 PM: ​
2:25:55 PM: Stored the Gatsby cache to speed up future builds.
2:25:55 PM: ​
2:25:55 PM: (netlify-plugin-gatsby-cache onPostBuild completed in 10.4s)
2:25:55 PM: ​
2:25:55 PM: ────────────────────────────────────────────────────────────────
2:25:55 PM:   4. Deploy site                                                
2:25:55 PM: ────────────────────────────────────────────────────────────────
2:25:55 PM: ​
2:25:55 PM: Starting to deploy site from 'public'
2:25:57 PM: Creating deploy tree asynchronously
2:25:57 PM: Creating deploy upload records
2:25:59 PM: 436 new files to upload
2:25:59 PM: 0 new functions to upload
2:26:07 PM: Site deploy was successfully initiated
2:26:07 PM: ​
2:26:07 PM: (Deploy site completed in 11.7s)
2:26:07 PM: ​
2:26:07 PM: ────────────────────────────────────────────────────────────────
2:26:07 PM:   Netlify Build Complete                                        
2:26:07 PM: ────────────────────────────────────────────────────────────────
2:26:07 PM: ​
2:26:07 PM: (Netlify Build completed in 18m 25.1s)
2:26:07 PM: Execution timed out after 20m45.963129662s
2:26:07 PM: Error running command: Command did not finish within the time limit
2:26:07 PM: Creating deploy upload records
2:26:07 PM: Failing build: Failed to build site
2:26:07 PM: Failed during stage 'building site': Command did not finish within the time limit
2:26:08 PM: Finished processing build request in 20m54.387510122s
2:26:21 PM: Starting post processing
2:26:21 PM: Post processing - HTML
2:27:30 PM: Post processing - header rules
2:27:31 PM: Post processing - redirect rules
2:27:31 PM: Post processing done
2:27:32 PM: Site is live ✨
```

**Comment by jlengstorf** [comment]
the build is timing out:

> Failed during stage 'building site': Command did not finish within the time limit

you can do as @qubis741 said and reduce the size of your build to get a cache in place (skipping some pages and/or images can help here), or you can open a topic on [the Netlify Forums](https://answers.netlify.com/) to request an increased time limit for builds that will let this build complete

I hope that helps!
