### ISSUE TITLE
Static HTML page doesn't update on deploy when data changes

### ISSUE THREAD

**Issue by qubis741** [jlengstorf/netlify-plugin-gatsby-cache#57]
Hello there,
I have a problem with this plugin, that static generated HTML page which loads as a first has cached old data. I am using Shopify as a source of data and I have set deploy to trigger on product create/update/deletion. So for example first second or 2 shows old list of products and then, when React hydrates, new list is loaded. When I clear cache in Netlify or when I update code with something on list page, new static site is generated. Is there any way to prevent static HTML sites to be cached via this plugin?

Setup:
```
"gatsby": "^2.25.3",
"netlify-plugin-gatsby-cache": "^0.3.2",
"react": "^16.9.0",
```

**Comment by jlengstorf** [comment]
hey there! this plugin is being replaced by official Netlify Gatsy support, so can you please switch to https://github.com/netlify/netlify-plugin-gatsby and see if it clears up the issue?

thanks!

**Comment by qubis741** [comment]
Hi, thanks for info but this problem still persist in new official Gatsby plugin. I have created issue there, if someone has same problem: https://github.com/netlify/netlify-plugin-gatsby/issues/86
