### ISSUE TITLE
beta link 404s

### ISSUE THREAD

**Issue by jasonLaster** [jlengstorf/netlify-plugin-gatsby-cache#6]
It looks like the beta link on the readme 404s

https://docs.netlify.com/configure-builds/plugins/?utm_source=github&utm_medium=netlify-plugin-gatsby-cache-jl&utm_campaign=devex

**Comment by jasonLaster** [comment]
Is this the link you're looking for?

https://www.netlify.com/build/plugins-beta/

**Comment by jlengstorf** [comment]
great question — @verythorough did this page move, or is it gone?

**Comment by verythorough** [comment]
We had expected that docs page to be published the day after I made the PR that added that updated the link. But our plans got delayed a bit. 🙈  They should be up by tomorrow, though!

**Comment by jlengstorf** [comment]
ah, okay — thanks!

**Comment by verythorough** [comment]
Alternatively, you _could_ use that other link: https://www.netlify.com/build/plugins-beta/

That'll also be updated soon so that the private beta form link will point to the docs page instead. Up to you which you'd prefer. :)

**Comment by verythorough** [comment]
Actually, I'm just going to put a quick redirect on the docs site for now.

**Comment by jlengstorf** [comment]
this link works now, so I'm going to close this — @verythorough let me know if we need to update anything!
