### ISSUE TITLE
Broken build logs links

### ISSUE THREAD

**Issue by vojtechruz** [jlengstorf/netlify-plugin-gatsby-cache#60]
Build logs referenced in readme are no longer loading. Netlify page opens but the log itself does not load. Tried in Brave and Edge browsers.

![image](https://github.com/jlengstorf/netlify-plugin-gatsby-cache/assets/7038612/30e83eb0-d88f-418f-894f-4b617ad4d243)

**Comment by jlengstorf** [comment]
this plugin is built into Netlify at this point, so if you uninstall this plugin you should get the caching by default (Netlify will show the Gatsby logo as part of your deploy log to confirm that it's working)

this plugin is no longer necessary and no longer maintained as a result. if you hit additional issues after switching to the Netlify version, hit up their support for next steps

thanks!
