### ISSUE TITLE
Should this plugin cache the publish directory?

### ISSUE THREAD

**Issue by ehmicky** [jlengstorf/netlify-plugin-gatsby-cache#9]
This plugin caches `PUBLISH_DIR` (renamed from `BUILD_DIR`) which is the "Publish directory" set in the UI or in the configuration file (`build.publish`). 

This issue is just to confirm that this is the intended behavior, i.e. that within Netlify, Gatsby always uses that publish directory to build files. Is this the case? Thanks!

**Comment by jlengstorf** [comment]
Gatsby always uses `public` — that's hard-coded into the build process
